import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import "@/app/global.css";
import { AlertProvider } from "@/app/hooks/useAlert";
import { Footer } from "@/app/components/Footer/index";
import MainNavbar from "@/app/components/Navbar/index";
import { ContactUsPopupProvider } from "@/app/components/Providers/ContactUsPopupProvider";
import { NAVBAR_DATA } from "@/app/lib/navbar-data";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          <ContactUsPopupProvider>
            <MainNavbar navbarData={NAVBAR_DATA} />
            {children}
            <Footer />
          </ContactUsPopupProvider>
        </AlertProvider>
      </body>
    </html>
  );
}

